### ISSUE TITLE
你好，在程序运行时报错：Requiring unknown module "react-native-sqlite-storage"

### ISSUE THREAD

**Issue by happyEgg** [cqm1994617/react-native-myCalendar#1]
怎么解决呀，我是在Genymotion模拟器上运行的

**Comment by cqm1994617** [comment]
报错好像说是没找到react-native-sqlite-storage模块。
你执行npm install时正常吗，顺便看看node_modules下有没有react-native-sqlite-storage这个文件夹，没有的话试试单独npm install react-native-sqlite-storage --save
